[package]
name = "rust-hyprland-json-unstable"
version = "0.4.0"
edition = "2024"

[dependencies]
cargo-bloat = "0.12.1"
clap = "4.5.54"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
